name: Release
on:
  push:
    tags: '*'
jobs:
  npm-release:
    name: NPM Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: guybedford/chomp-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm publish --dry-run --tag ${{ github.ref }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


  github-release:
    name: GitHub Release
    needs: npm-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
